version: "3"

services:
  jupyter-pyspark-cluster:
    build:
      context: ./dockerfiles/jupyter
      dockerfile: Dockerfile
    container_name: jupyter-pyspark-cluster
    ports:
      - 8888:8888
      - 4040:4040
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
      - ./scripts:/home/jovyan/work/scripts
  spark-master:
    image: bitnami/spark:3.3.3
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/jovyan/work/data
      - ./scripts:/home/jovyan/work/scripts
  spark-worker:
    build:
      context: ./dockerfiles/spark_worker
      dockerfile: Dockerfile
    image: bitnami/spark:3.3.3
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/home/jovyan/work/data